#! /usr/bin/env python
# encoding: utf-8
# vim: noexpandtab

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'raytrace'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'raytrace.cpp',
		'trace2.cpp',
		'trace3.cpp',
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../public/tier2',
		'../public/tier3',
		'../utils/common'
	]

	defines = []

	libs = ['tier0', 'tier1', 'tier2', 'vstdlib', 'mathlib']

	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

