#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'dedicated_launcher'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):

	source = ['main.cpp']
	includes = ['../public', '../public/tier0']
	defines = []
	libs = []
	linkflags = []

	if bld.env.DEST_OS != 'win32':
		libs += [ 'DL' ]
	else:
		libs += ['USER32', 'SHELL32']
		source += ['dedicated_main.rc']

	if bld.env.DEST_OS != 'win32':
		if bld.env.DEST_OS == "darwin":
			linkflags += ['-rpath', '@loader_path/bin/']
		else:
			linkflags += ['-rpath', '$ORIGIN/bin/']

	install_path = bld.env.BINDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		linkflags = linkflags,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

