#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'steam_api'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'steam_api.cpp'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = []

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		install_path = bld.env.LIBDIR,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

