#! /usr/bin/env python
# encoding: utf-8
# vim: noexpandtab

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'vvis'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('PROTECTED_THINGS_DISABLE', 1)
	return

def build(bld):
	source = [
		'WaterDist.cpp',
		'flow.cpp',
		'vvis.cpp',
		'../common/bsplib.cpp',
		'../common/cmdlib.cpp',
		'../common/scriplib.cpp',
		'../common/filesystem_tools.cpp',
		'../common/pacifier.cpp',
		'../common/threads.cpp',
		'../../public/collisionutils.cpp',
		'../../public/filesystem_helpers.cpp',
		'../../public/filesystem_init.cpp',
		'../../public/loadcmdline.cpp',
		'../../public/lumpfiles.cpp',
		'../../public/zip_utils.cpp',
		'../../filesystem/linux_support.cpp',
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'mpivis.cpp',
			'../common/mpi_stats.cpp',
			'../common/MySqlDatabase.cpp',
			'../common/tools_minidump.cpp',
			'../common/vmpi_tools_shared.cpp',
			'../common/scratchpad_helpers.cpp',
			'../../public/scratchpad3d.cpp',
		]

	includes = [
		'.',
		'../common',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../public/tier2',
		'../../public/tier3',
		'../../public/mathlib'
	]

	defines = []

	libs = ['tier0', 'tier1', 'tier2', 'tier3', 'mathlib', 'lzma', 'vstdlib']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

