#! /usr/bin/env python
# encoding: utf-8
# vim: noexpandtab

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'vpk'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'packtest.cpp',
		'../../public/filesystem_init.cpp',
		'../../filesystem/linux_support.cpp',
	]

	includes = [
		'.',
		'../common',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../public/tier2',
	]

	defines = []

	libs = [
		'tier0', 'tier1', 'tier2', 'tier3',
		'vstdlib',
		'mathlib',
		'vpklib',
		'bitmap',
	]

	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	install_path = bld.env.BINDIR

	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

