res2c awards.gif binResources CTFStatsReport::gifAwards
res2c bgleft.jpg binResources CTFStatsReport::jpgBgLeft
res2c bgtop.jpg binResources CTFStatsReport::jpgBgTop
res2c boxscore.gif binResources CTFStatsReport::gifBoxScore
res2c game.dialog.off.gif binResources CTFStatsReport::gifGameDialogOff
res2c game.dialog.on.gif binResources CTFStatsReport::gifGameDialogOn
res2c match.statistics.off.gif binResources CTFStatsReport::gifMatchStatsOff
res2c match.statistics.on.gif binResources CTFStatsReport::gifMatchStatsOn
res2c scores.gif binResources CTFStatsReport::gifScores
res2c server.settings.off.gif binResources CTFStatsReport::gifServerSettingsOff
res2c server.settings.on.gif binResources CTFStatsReport::gifServerSettingsOn
res2c player.statistics.off.gif binResources CTFStatsReport::gifPlayerStatsOff
res2c player.statistics.on.gif binResources CTFStatsReport::gifPlayerStatsOn
res2c detailed.gif binResources CTFStatsReport::gifDetailedScores
