#! /usr/bin/env python
# encoding: utf-8
# vim: noexpandtab

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'lzma'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('_NO_EXCEPTIONS', 1)
	conf.define('_LZMA_PROB32', 1)
	conf.define('_7ZIP_ST', 1)
	return

def build(bld):
	source = [
		'lzma.cpp',
		'C/LzmaEnc.c',
		'C/LzmaDec.c',
		'C/LzFind.c',
	]

	includes = [
		'.',
		'./C',
		'../common',
		'../../public',
	]

	defines = []

	libs = []

	if bld.env.DEST_OS == 'win32':
		libs += ['ADVAPI32', 'WS2_32']
	else:
		libs += ['DL', 'M', 'LOG']

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

