#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'vtf'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'convert_x360.cpp',
		#$File	"s3tc_decode.cpp" #	[$WINDOWS]
		'vtf.cpp'
		#$File	"vtf_x360.cpp"#		[$X360]
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common'
	]

	defines = []

	libs = []

	install_path = bld.env.PREFIX

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

