#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'bzip2'

def options(opt):
	# stub
	return

def configure(conf):
	if conf.env.DEST_OS != 'win32':
		conf.env.append_unique('CFLAGS',['-std=gnu11'])

def build(bld):
	source = [
		'blocksort.c',
		'bzip2.c',
		'bzlib.c',
		'compress.c',
		'crctable.c',
		'decompress.c',
		'huffman.c',
		'randtable.c'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common'
	]

	defines = []

	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

