#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'bugreporter_public'

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	source = [
		'../../public/blockingudpsocket.cpp',
		'bugreporter_public.cpp',
		'bugreporter_upload.cpp'
	]

	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../public/vstdlib',
		'../../public/mathlib',
		'../common'
	]

	defines = []

	libs = ['tier0', 'tier1', 'vstdlib', 'appframework', 'mathlib']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

