#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'unicode'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('UNICODE_EXPORTS', 1)

def build(bld):
	if bld.env.DEST_OS != 'win32':
		return

	source = [
		'unicode.cpp',
		'../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1'
	]

	defines = []

	libs = ['tier0','tier1','tier2','vstdlib','mathlib', 'USER32']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

