//========= Copyright Valve Corporation, All rights reserved. ============//
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vxconsole.rc
//
#define MENU_PROFILE                    4
#define MENU_CPUPROFILE                 4
#define MENU_VXCONSOLE                  100
#define IDD_VXCONSOLE                   104
#define IDD_CONFIG                      111
#define IDC_LABEL                       113
#define IDD_SYNCFILES                   116
#define MENU_SHOWTEXTURES               118
#define MENU_TEXPROFILE                 120
#define MENU_BINDOPTIONS                122
#define IDD_MODIFYBIND                  123
#define MENU_SHOWMATERIALS              124
#define MENU_SHOWSOUNDS                 125
#define MENU_SHOWMEMORYDUMP             127
#define IDD_BUG                         128
#define MENU_TIMESTAMPLOG               129
#define IDD_EXCLUDEPATHS                131
#define IDD_INSTALL                     132
#define MENU_MEMPROFILE                 133
#define IDI_VXCONSOLE                   200
#define IDI_DISCONNECTED                201
#define IDI_CONNECT1_ON                 202
#define IDI_CONNECT2_ON                 203
#define IDI_CONNECT2_OFF                204
#define IDC_COMMAND                     1000
#define IDC_OUTPUT                      1010
#define IDC_CONFIG_XBOXNAME             1015
#define IDC_CONFIG_REMOTEPATH           1016
#define IDC_CONFIG_LOCALPATH            1017
#define IDC_CONFIG_PING                 1018
#define IDC_OK                          1019
#define IDC_CANCEL                      1020
#define IDC_CONFIG_CLEARONCONNECT       1021
#define IDC_CONFIG_TARGETPATH           1022
#define IDC_CONFIG_XBELOCALPATH         1023
#define IDC_CONFIG_XEXLOCALPATH         1023
#define IDC_CONFIG_XBETARGETPATH        1024
#define IDC_CONFIG_XEXTARGETPATH        1024
#define IDC_CONFIG_INSTALLPATH          1025
#define IDC_CONFIG_LOADSYMBOLS          1028
#define IDC_SYNCFILES_LOCALPATH         1029
#define IDC_SYNCFILES_TARGETPATH        1030
#define IDC_SYNCFILES_FORCESYNC         1035
#define IDC_SYNCFILES_NOWRITE           1036
#define IDC_SYNCFILES_DELETEORPHANS     1037
#define IDC_CONFIG_SAMPLEFILE           1038
#define IDC_SYNCFILES_VERBOSE           1038
#define IDC_CONFIG_SAMPLELOCAL          1039
#define IDC_SYNCFILES_ANDEXISTSONXBOX   1039
#define IDC_CONFIG_SAMPLETARGET         1040
#define IDC_CONFIG_XBEFORCESYNC         1045
#define IDC_CONFIG_XEXFORCESYNC         1045
#define IDC_CONFIG_XBESYNCONCONNECT     1046
#define IDC_CONFIG_XEXSYNCONCONNECT     1046
#define IDC_MODIFYBIND_MENUNAME         1050
#define IDC_MODIFYBIND_COMMAND          1051
#define IDC_MODIFYBIND_KEYCODE          1052
#define IDC_CONFIG_ALWAYSAUTOCONNECT    1053
#define IDC_CONFIG_STARTMINIMIZED       1054
#define IDC_CONFIG_CAPTUREDEBUGSPEW     1055
#define IDC_BUG_CLEARFORM               1056
#define IDC_BUG_TITLE                   1057
#define IDC_BUG_DESCRIPTION             1058
#define IDC_BUG_CLEARFORM2              1059
#define IDC_BUG_UPDATE                  1059
#define IDC_BUG_INCLUDEBSP              1060
#define IDC_BUG_SAVEGAME                1061
#define IDC_BUG_INCLUDEVMF              1062
#define IDC_BUG_TAKESHOT                1063
#define IDC_BUG_SEVERITY                1065
#define IDC_BUG_REPORTTYPE              1066
#define IDC_BUG_PRIORITY                1067
#define IDC_BUG_AREA                    1068
#define IDC_BUG_TAKESHOT_LABEL          1069
#define IDC_BUG_SAVEGAME_LABEL          1070
#define IDC_BUG_INCLUDEBSP_LABEL        1071
#define IDC_BUG_INCLUDEVMF_LABEL        1072
#define IDC_BUG_POSITION_LABEL          1073
#define IDC_BUG_ORIENTATION_LABEL       1074
#define IDC_BUG_MAP_LABEL               1075
#define IDC_BUG_BUILD_LABEL             1076
#define IDC_BUG_SUBMITTER_LABEL         1077
#define IDC_BUG_MAPNUMBER               1078
#define IDC_BUG_SUBMIT                  1079
#define IDC_BUG_SEVERITY2               1080
#define IDC_BUG_OWNER                   1080
#define IDC_BUG_GAME                    1082
#define IDC_CHECK1                      1083
#define IDC_BUG_COMPRESS_SCREENSHOT     1083
#define IDC_PATHS_LINKGAMEDIRS          1083
#define IDC_INSTALL_FORCESYNC           1083
#define IDC_PATHS_TREE                  1085
#define IDC_PATHS_RESCAN                1086
#define IDC_PATHS_EXPAND                1087
#define IDC_PATHS_COLLAPSE              1088
#define IDC_INSTALL_LIST                1088
#define IDC_INSTALL_REFRESH             1089
#define IDC_CHECK2                      1091
#define IDC_INSTALL_CLEANTARGET         1091
#define IDR_MAIN_ACCEL                  3000
#define IDM_CONNECT                     40002
#define IDM_DEBUGMONITOR                40004
#define IDM_DEBUGCOMMANDS               40008
#define IDM_AUTOCONNECT                 40009
#define IDM_DISCONNECT                  40013
#define IDM_EXIT                        40017
#define IDM_CONFIG                      40018
#define IDM_DEBUGMEMORY                 40019
#define IDM_FILELOG                     40021
#define IDM_CLEARLOG                    40026
#define IDM_ENABLELOG                   40027
#define IDM_REFRESHLOG                  40031
#define ID_LOG_SUMMARY                  40032
#define IDM_SUMMARYLOG                  40035
#define ID_Menu                         40048
#define IDM_PROFILESAMPLES              40064
#define IDM_PROFILEHISTORY              40066
#define IDM_SYNCTARGET                  40073
#define IDM_SYNCIFNEWER                 40074
#define IDM_ENABLEFILESERVING           40075
#define ID_CONNECTION_FILESERVING       40076
#define IDM_FILESERVING_LOCALONLY       40080
#define IDM_FILESERVING_REMOTEONLY      40081
#define IDM_FILESERVING_LOCALFIRST      40083
#define IDM_FILESYNC_OFF                40088
#define IDM_FILESYNC_ALWAYS             40089
#define IDM_FILESYNC_IFNEWER            40090
#define IDM_EXPORTLOG                   40092
#define ID_Menu40094                    40094
#define IDM_SYMBOLS_ADDRESS             40106
#define IDM_SYMBOLS_FUNCTIONNAME        40110
#define IDM_SYMBOLS_MODULEANDLINE       40112
#define IDM_SYMBOLS_FILEPATHANDLINE     40114
#define IDM_SYMBOLS_LOAD                40116
#define IDM_SYNCFILES                   40117
#define IDM_SYMBOLS_DETAILS             40119
#define IDM_OPTIONS_TREEVIEW            40121
#define ID_Menu40123                    40123
#define IDM_SHOWMATERIALS               40124
#define IDM_REFRESH                     40127
#define IDM_SHOWRESOURCES_TEXTURES      40130
#define IDM_OPTIONS_CURRENTFRAME        40132
#define IDM_OPTIONS_SUMMARY             40135
#define IDM_OPTIONS_REFRESH             40136
#define IDM_OPTIONS_EXPORT              40137
#define IDM_OPTIONS_FULLPATH            40139
#define ID_CONNECTION_PROFILING         40140
#define ID_PROFILING_CPU                40141
#define ID_PROFILING_TEXTURE            40142
#define ID_CONNECTION_TEXTUREPROFILING  40147
#define IDM_CPU_SAMPLES                 40148
#define IDM_CPU_HISTORY                 40149
#define IDM_SHOWRESOURCES_MATERIALS     40154
#define IDM_SHOWRESOURCES_MODELS        40155
#define ID_CONNECTION_EE                40157
#define IDM_CPUPROFILE_TICKMARKS        40160
#define IDM_CPUPROFILE_COLORS           40161
#define IDM_CPUPROFILE_ZOOMIN           40162
#define IDM_CPUPROFILE_ZOOMOUT          40163
#define IDM_CPUPROFILE_ENABLE           40164
#define IDM_TEXPROFILE_TICKMARKS        40166
#define IDM_TEXPROFILE_COLORS           40168
#define IDM_TEXPROFILE_ZOOMIN           40172
#define IDM_TEXPROFILE_ZOOMOUT          40173
#define IDM_TEXPROFILE_ENABLE           40174
#define IDM_TEXPROFILE_CURRENTFRAME     40176
#define ID_Menu40177                    40177
#define ID_VPROFILING_SHOWTEXTURE       40178
#define ID_Menu40189                    40189
#define IDM_BINDOPTIONS_MODIFY          40192
#define IDM_BINDOPTIONS_DELETE          40193
#define IDM_TIMESTAMPLOG                50502
#define IDM_CPUPROFILE_FPSLABELS        50505
#define IDM_SHOWRESOURCES_SOUNDS        50509
#define IDM_OPTIONS_PLAYSOUND           50513
#define IDM_D3D_SAMPLES                 50516
#define IDM_D3D_HISTORY                 50517
#define IDM_MEMORYDUMP                  50520
#define IDM_OPTIONS_BYTES               50527
#define IDM_OPTIONS_KILOBYTES           50530
#define IDM_OPTIONS_MEGABYTES           50531
#define IDM_OPTIONS_COLLAPSEOUTPUT      50533
#define IDM_SYNCINSTALL                 50535
#define ID_Menu50536                    50536
#define IDM_FILESYNC_ANDEXISTSONTARGET  50539
#define ID_CONNECTION_SEARCHPATHS       50540
#define ID_SEARCHPATHS_NOZIPS           50541
#define ID_SEARCHPATHS_PAKFILESFIRST    50542
#define ID_SEARCHPATHS_PAKFILES         50543
#define ID_Menu50546                    50546
#define IDM_SYNCINSTALL_TODVD           50547
#define IDM_SYNCINSTALL_TOHDD           50548
#define IDM_SHOWRESOURCES_BUG           50550
#define IDM_BUG                         50552
#define IDM_SYNCXEX                     50553
#define IDM_DEBUGSPEW                   50557
#define IDM_CAPTUREGAMESPEW             50560
#define IDM_CAPTUREDEBUGSPEW            50561
#define ID_CONNECTION_DVDEXCLUDEPATHS   50562
#define IDM_DVDEXCLUDEPATHS             50563
#define IDM_EXCLUDEPATHS                50564
#define ID_OPTIONS_SHOWTEXTURE          50565
#define IDM_OPTIONS_SHOWTEXTURE         50566
#define IDM_OPTIONS_DRAWTEXTURE         50567
#define ID_OPTIONS_HIDETEXTURE          50568
#define IDM_OPTIONS_HIDETEXTURE         50569
#define ID_PROFILING_SHOWMEMORYUSAGE    50570
#define IDM_SHOWMEMORYUSAGE             50571
#define IDM_SHOWFREEMEMORY              50572
#define ID_OPTIONS_TICKMARKS            50573
#define ID_OPTIONS_ZOOMIN               50574
#define ID_OPTIONS_ZOOMOUT              50575
#define ID_OPTIONS_ENABLE               50576
#define IDM_MEMPROFILE_TICKMARKS        50577
#define IDM_MEMPROFILE_ZOOMIN           50578
#define IDM_MEMPROFILE_ZOOMOUT          50579
#define IDM_MEMPROFILE_ENABLE           50580
#define ID_OPTIONS_COLORS               50581
#define IDM_MEMPROFILE_COLORS           50582
#define ID_OPTIONS_CLEAR                50583
#define IDM_OPTIONS_CLEAR               50584
#define ID_PROFILING_TESTINGMODE        50585
#define IDM_PLAYTESTMODE                50586
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         50587
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
