#! /usr/bin/env python
# encoding: utf-8
# vim: noexpandtab

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'vrad_launcher'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'vrad_launcher.cpp'
	]

	includes = [
		'.',
		'../common',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../public/tier2',
	]

	defines = []

	libs = ['tier0', 'tier1', 'tier2', 'vrad']

	if bld.env.DEST_OS == 'win32':
		libs += ['ADVAPI32', 'WS2_32']
	else:
		libs += ['DL', 'LOG']

	install_path = bld.env.BINDIR

	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

