#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'datamodel'

def options(opt):
	return

def configure(conf):
	conf.define('DATAMODEL_LIB',1)

def build(bld):
	source = [
		'clipboardmanager.cpp',
		'datamodel.cpp',
		'dependencygraph.cpp',
		'dmattribute.cpp',
		'dmelement.cpp',
		'dmelementdictionary.cpp',
		'dmelementfactoryhelper.cpp',
		'DmElementFramework.cpp',
		'dmserializerbinary.cpp',
		'dmserializerkeyvalues.cpp',
		'dmserializerkeyvalues2.cpp',
		'undomanager.cpp'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../common'
	]

	defines = []

	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

