#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'mathlibtest'

def options(opt):
	return

def configure(conf):
	conf.define('TIER2TEST_EXPORTS', 1)

def build(bld):
	source = ['mathlib_performance_test.cpp', 'mathlib_test.cpp']
	includes = ['../../public', '../../public/tier0']
	defines = []
	libs = ['tier0', 'tier1','tier2', 'mathlib', 'unitlib']

	if bld.env.DEST_OS != 'win32':
		libs += [ 'DL', 'LOG' ]
	else:
		libs += ['USER32', 'SHELL32']

	install_path = bld.env.TESTDIR
	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
