#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'appframework'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'AppSystemGroup.cpp',
		'../public/filesystem_init.cpp',
	]

	if bld.env.SDL:
		source += [
			'sdlmgr.cpp'
		]

	if bld.env.DEST_OS == 'darwin' and bld.env.GL:
		source += ['glmrendererinfo_osx.mm']


	if bld.env.DEST_OS == 'win32':
		source += [
			'vguimatsysapp.cpp',
			'winapp.cpp'
		]
	else:
		source += [
			'posixapp.cpp',#		[$POSIX]
		]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1'
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = []

	if bld.env.DEST_OS == 'darwin':
		libs += ['FOUNDATION', 'APPKIT', 'IOKIT']

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

