#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'vaudio_minimp3'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'mp3codecs.cpp',
		'../../../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../../../public/tier1',
		'../../../public/',
		'../../../thirdparty/minimp3'
	]

	defines = []

	libs = ['tier0','tier1','vstdlib']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

