#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'scenefilecache'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('_WINDOWS',1) # WTF? this defined in original vpc file
	conf.define('PROTECTED_THINGS_ENABLE',1)

def build(bld):
	source = [
		'SceneFileCache.cpp'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../game/shared'
	]

	defines = []

	libs = ['tier0','tier1']

	install_path = bld.env.PREFIX

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

