#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'scenefilecache'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('_WINDOWS',1) # WTF? this defined in original vpc file
	#conf.define('PROTECTED_THINGS_ENABLE',1) # conflicts with stlport

def build(bld):
	source = [
		'SceneFileCache.cpp',
		'../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1',
		'../game/shared'
	]

	defines = []

	libs = ['tier0','tier1']

	if bld.env.DEST_OS == 'android':
		libs += ['ANDROID_SUPPORT']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

