p4 add ./foo.bat
p4 add ./Lib/allegrocl/allegrocl.swg
p4 add ./Lib/allegrocl/inout_typemaps.i
p4 add ./Lib/allegrocl/longlongs.i
p4 add ./Lib/allegrocl/std_list.i
p4 add ./Lib/allegrocl/std_string.i
p4 add ./Lib/allegrocl/typemaps.i
p4 add ./Lib/allkw.swg
p4 add ./Lib/attribute.i
p4 add ./Lib/carrays.i
p4 add ./Lib/cdata.i
p4 add ./Lib/cffi/cffi.swg
p4 add ./Lib/chicken/chicken.swg
p4 add ./Lib/chicken/chickenkw.swg
p4 add ./Lib/chicken/chickenrun.swg
p4 add ./Lib/chicken/extra-install.list
p4 add ./Lib/chicken/multi-generic.scm
p4 add ./Lib/chicken/std_string.i
p4 add ./Lib/chicken/swigclosprefix.scm
p4 add ./Lib/chicken/tinyclos-multi-generic.patch
p4 add ./Lib/chicken/typemaps.i
p4 add ./Lib/clisp/clisp.swg
p4 add ./Lib/cmalloc.i
p4 add ./Lib/constraints.i
p4 add ./Lib/cpointer.i
p4 add ./Lib/csharp/boost_shared_ptr.i
p4 add ./Lib/csharp/csharp.swg
p4 add ./Lib/csharp/csharphead.swg
p4 add ./Lib/csharp/csharpkw.swg
p4 add ./Lib/csharp/director.swg
p4 add ./Lib/csharp/enums.swg
p4 add ./Lib/csharp/enumsimple.swg
p4 add ./Lib/csharp/enumtypesafe.swg
p4 add ./Lib/csharp/std_common.i
p4 add ./Lib/csharp/std_deque.i
p4 add ./Lib/csharp/std_except.i
p4 add ./Lib/csharp/std_map.i
p4 add ./Lib/csharp/std_pair.i
p4 add ./Lib/csharp/std_string.i
p4 add ./Lib/csharp/std_vector.i
p4 add ./Lib/csharp/std_wstring.i
p4 add ./Lib/csharp/stl.i
p4 add ./Lib/csharp/typemaps.i
p4 add ./Lib/csharp/wchar.i
p4 add ./Lib/cstring.i
p4 add ./Lib/cwstring.i
p4 add ./Lib/exception.i
p4 add ./Lib/gcj/cni.i
p4 add ./Lib/gcj/cni.swg
p4 add ./Lib/gcj/javaprims.i
p4 add ./Lib/guile/common.scm
p4 add ./Lib/guile/cplusplus.i
p4 add ./Lib/guile/extra-install.list
p4 add ./Lib/guile/ghinterface.i
p4 add ./Lib/guile/guile.i
p4 add ./Lib/guile/guilemain.i
p4 add ./Lib/guile/guile_gh.swg
p4 add ./Lib/guile/guile_gh_run.swg
p4 add ./Lib/guile/guile_scm.swg
p4 add ./Lib/guile/guile_scm_run.swg
p4 add ./Lib/guile/interpreter.i
p4 add ./Lib/guile/list-vector.i
p4 add ./Lib/guile/Makefile
p4 add ./Lib/guile/pointer-in-out.i
p4 add ./Lib/guile/ports.i
p4 add ./Lib/guile/std_common.i
p4 add ./Lib/guile/std_deque.i
p4 add ./Lib/guile/std_except.i
p4 add ./Lib/guile/std_map.i
p4 add ./Lib/guile/std_pair.i
p4 add ./Lib/guile/std_string.i
p4 add ./Lib/guile/std_vector.i
p4 add ./Lib/guile/stl.i
p4 add ./Lib/guile/swigrun.i
p4 add ./Lib/guile/typemaps.i
p4 add ./Lib/inttypes.i
p4 add ./Lib/java/arrays_java.i
p4 add ./Lib/java/boost_shared_ptr.i
p4 add ./Lib/java/director.swg
p4 add ./Lib/java/enums.swg
p4 add ./Lib/java/enumsimple.swg
p4 add ./Lib/java/enumtypesafe.swg
p4 add ./Lib/java/enumtypeunsafe.swg
p4 add ./Lib/java/java.swg
p4 add ./Lib/java/javahead.swg
p4 add ./Lib/java/javakw.swg
p4 add ./Lib/java/std_common.i
p4 add ./Lib/java/std_deque.i
p4 add ./Lib/java/std_except.i
p4 add ./Lib/java/std_map.i
p4 add ./Lib/java/std_pair.i
p4 add ./Lib/java/std_string.i
p4 add ./Lib/java/std_vector.i
p4 add ./Lib/java/std_wstring.i
p4 add ./Lib/java/stl.i
p4 add ./Lib/java/typemaps.i
p4 add ./Lib/java/various.i
p4 add ./Lib/linkruntime.c
p4 add ./Lib/lua/carrays.i
p4 add ./Lib/lua/lua.swg
p4 add ./Lib/lua/luarun.swg
p4 add ./Lib/lua/luaruntime.swg
p4 add ./Lib/lua/luatypemaps.swg
p4 add ./Lib/lua/lua_fnptr.i
p4 add ./Lib/lua/std_common.i
p4 add ./Lib/lua/std_deque.i
p4 add ./Lib/lua/std_except.i
p4 add ./Lib/lua/std_map.i
p4 add ./Lib/lua/std_pair.i
p4 add ./Lib/lua/std_string.i
p4 add ./Lib/lua/std_vector.i
p4 add ./Lib/lua/stl.i
p4 add ./Lib/lua/typemaps.i
p4 add ./Lib/lua/wchar.i
p4 add ./Lib/lua/_std_common.i
p4 add ./Lib/math.i
p4 add ./Lib/modula3/modula3.swg
p4 add ./Lib/modula3/modula3head.swg
p4 add ./Lib/modula3/typemaps.i
p4 add ./Lib/mzscheme/Makefile
p4 add ./Lib/mzscheme/mzrun.swg
p4 add ./Lib/mzscheme/mzscheme.swg
p4 add ./Lib/mzscheme/std_common.i
p4 add ./Lib/mzscheme/std_deque.i
p4 add ./Lib/mzscheme/std_map.i
p4 add ./Lib/mzscheme/std_pair.i
p4 add ./Lib/mzscheme/std_string.i
p4 add ./Lib/mzscheme/std_vector.i
p4 add ./Lib/mzscheme/stl.i
p4 add ./Lib/mzscheme/typemaps.i
p4 add ./Lib/ocaml/carray.i
p4 add ./Lib/ocaml/class.swg
p4 add ./Lib/ocaml/cstring.i
p4 add ./Lib/ocaml/director.swg
p4 add ./Lib/ocaml/extra-install.list
p4 add ./Lib/ocaml/libswigocaml.h
p4 add ./Lib/ocaml/ocaml.i
p4 add ./Lib/ocaml/ocaml.swg
p4 add ./Lib/ocaml/ocamldec.swg
p4 add ./Lib/ocaml/ocamlkw.swg
p4 add ./Lib/ocaml/preamble.swg
p4 add ./Lib/ocaml/std_common.i
p4 add ./Lib/ocaml/std_complex.i
p4 add ./Lib/ocaml/std_deque.i
p4 add ./Lib/ocaml/std_list.i
p4 add ./Lib/ocaml/std_map.i
p4 add ./Lib/ocaml/std_pair.i
p4 add ./Lib/ocaml/std_string.i
p4 add ./Lib/ocaml/std_vector.i
p4 add ./Lib/ocaml/stl.i
p4 add ./Lib/ocaml/swig.ml
p4 add ./Lib/ocaml/swig.mli
p4 add ./Lib/ocaml/swigp4.ml.in
p4 add ./Lib/ocaml/typecheck.i
p4 add ./Lib/ocaml/typemaps.i
p4 add ./Lib/ocaml/typeregister.swg
p4 add ./Lib/perl5/attribute.i
p4 add ./Lib/perl5/carrays.i
p4 add ./Lib/perl5/cdata.i
p4 add ./Lib/perl5/cmalloc.i
p4 add ./Lib/perl5/cni.i
p4 add ./Lib/perl5/cpointer.i
p4 add ./Lib/perl5/cstring.i
p4 add ./Lib/perl5/exception.i
p4 add ./Lib/perl5/extra-install.list
p4 add ./Lib/perl5/factory.i
p4 add ./Lib/perl5/jstring.i
p4 add ./Lib/perl5/Makefile.in
p4 add ./Lib/perl5/Makefile.pl
p4 add ./Lib/perl5/noembed.h
p4 add ./Lib/perl5/perl5.swg
p4 add ./Lib/perl5/perlerrors.swg
p4 add ./Lib/perl5/perlfragments.swg
p4 add ./Lib/perl5/perlhead.swg
p4 add ./Lib/perl5/perlinit.swg
p4 add ./Lib/perl5/perlkw.swg
p4 add ./Lib/perl5/perlmacros.swg
p4 add ./Lib/perl5/perlmain.i
p4 add ./Lib/perl5/perlopers.swg
p4 add ./Lib/perl5/perlprimtypes.swg
p4 add ./Lib/perl5/perlrun.swg
p4 add ./Lib/perl5/perlruntime.swg
p4 add ./Lib/perl5/perlstrings.swg
p4 add ./Lib/perl5/perltypemaps.swg
p4 add ./Lib/perl5/perluserdir.swg
p4 add ./Lib/perl5/reference.i
p4 add ./Lib/perl5/std_common.i
p4 add ./Lib/perl5/std_deque.i
p4 add ./Lib/perl5/std_except.i
p4 add ./Lib/perl5/std_list.i
p4 add ./Lib/perl5/std_map.i
p4 add ./Lib/perl5/std_pair.i
p4 add ./Lib/perl5/std_string.i
p4 add ./Lib/perl5/std_vector.i
p4 add ./Lib/perl5/stl.i
p4 add ./Lib/perl5/typemaps.i
p4 add ./Lib/php4/const.i
p4 add ./Lib/php4/globalvar.i
p4 add ./Lib/php4/php4.swg
p4 add ./Lib/php4/php4init.swg
p4 add ./Lib/php4/php4kw.swg
p4 add ./Lib/php4/php4run.swg
p4 add ./Lib/php4/phppointers.i
p4 add ./Lib/php4/std_common.i
p4 add ./Lib/php4/std_deque.i
p4 add ./Lib/php4/std_map.i
p4 add ./Lib/php4/std_pair.i
p4 add ./Lib/php4/std_string.i
p4 add ./Lib/php4/std_vector.i
p4 add ./Lib/php4/stl.i
p4 add ./Lib/php4/typemaps.i
p4 add ./Lib/php4/utils.i
p4 add ./Lib/pike/pike.swg
p4 add ./Lib/pike/pikekw.swg
p4 add ./Lib/pike/pikerun.swg
p4 add ./Lib/pike/std_string.i
p4 add ./Lib/pointer.i
p4 add ./Lib/python/argcargv.i
p4 add ./Lib/python/attribute.i
p4 add ./Lib/python/boost_shared_ptr.i
p4 add ./Lib/python/carrays.i
p4 add ./Lib/python/ccomplex.i
p4 add ./Lib/python/cdata.i
p4 add ./Lib/python/cmalloc.i
p4 add ./Lib/python/cni.i
p4 add ./Lib/python/complex.i
p4 add ./Lib/python/cpointer.i
p4 add ./Lib/python/cstring.i
p4 add ./Lib/python/cwstring.i
p4 add ./Lib/python/defarg.swg
p4 add ./Lib/python/director.swg
p4 add ./Lib/python/embed.i
p4 add ./Lib/python/embed15.i
p4 add ./Lib/python/exception.i
p4 add ./Lib/python/factory.i
p4 add ./Lib/python/file.i
p4 add ./Lib/python/implicit.i
p4 add ./Lib/python/jstring.i
p4 add ./Lib/python/Makefile.in
p4 add ./Lib/python/pyapi.swg
p4 add ./Lib/python/pybackward.swg
p4 add ./Lib/python/pyclasses.swg
p4 add ./Lib/python/pycomplex.swg
p4 add ./Lib/python/pycontainer.swg
p4 add ./Lib/python/pydocs.swg
p4 add ./Lib/python/pyerrors.swg
p4 add ./Lib/python/pyfragments.swg
p4 add ./Lib/python/pyhead.swg
p4 add ./Lib/python/pyinit.swg
p4 add ./Lib/python/pyiterators.swg
p4 add ./Lib/python/pymacros.swg
p4 add ./Lib/python/pyopers.swg
p4 add ./Lib/python/pyprimtypes.swg
p4 add ./Lib/python/pyrun.swg
p4 add ./Lib/python/pyruntime.swg
p4 add ./Lib/python/pystdcommon.swg
p4 add ./Lib/python/pystrings.swg
p4 add ./Lib/python/python.swg
p4 add ./Lib/python/pythonkw.swg
p4 add ./Lib/python/pythreads.swg
p4 add ./Lib/python/pytuplehlp.swg
p4 add ./Lib/python/pytypemaps.swg
p4 add ./Lib/python/pyuserdir.swg
p4 add ./Lib/python/pywstrings.swg
p4 add ./Lib/python/README
p4 add ./Lib/python/std_alloc.i
p4 add ./Lib/python/std_basic_string.i
p4 add ./Lib/python/std_carray.i
p4 add ./Lib/python/std_char_traits.i
p4 add ./Lib/python/std_common.i
p4 add ./Lib/python/std_complex.i
p4 add ./Lib/python/std_container.i
p4 add ./Lib/python/std_deque.i
p4 add ./Lib/python/std_except.i
p4 add ./Lib/python/std_ios.i
p4 add ./Lib/python/std_iostream.i
p4 add ./Lib/python/std_list.i
p4 add ./Lib/python/std_map.i
p4 add ./Lib/python/std_multimap.i
p4 add ./Lib/python/std_multiset.i
p4 add ./Lib/python/std_pair.i
p4 add ./Lib/python/std_set.i
p4 add ./Lib/python/std_sstream.i
p4 add ./Lib/python/std_streambuf.i
p4 add ./Lib/python/std_string.i
p4 add ./Lib/python/std_vector.i
p4 add ./Lib/python/std_vectora.i
p4 add ./Lib/python/std_wios.i
p4 add ./Lib/python/std_wiostream.i
p4 add ./Lib/python/std_wsstream.i
p4 add ./Lib/python/std_wstreambuf.i
p4 add ./Lib/python/std_wstring.i
p4 add ./Lib/python/stl.i
p4 add ./Lib/python/typemaps.i
p4 add ./Lib/python/wchar.i
p4 add ./Lib/r/cdata.i
p4 add ./Lib/r/exception.i
p4 add ./Lib/r/r.swg
p4 add ./Lib/r/rcontainer.swg
p4 add ./Lib/r/rfragments.swg
p4 add ./Lib/r/ropers.swg
p4 add ./Lib/r/rrun.swg
p4 add ./Lib/r/rstdcommon.swg
p4 add ./Lib/r/rtype.swg
p4 add ./Lib/r/srun.swg
p4 add ./Lib/r/std_alloc.i
p4 add ./Lib/r/std_common.i
p4 add ./Lib/r/std_container.i
p4 add ./Lib/r/std_deque.i
p4 add ./Lib/r/std_except.i
p4 add ./Lib/r/std_pair.i
p4 add ./Lib/r/std_string.i
p4 add ./Lib/r/std_vector.i
p4 add ./Lib/r/stl.i
p4 add ./Lib/r/typemaps.i
p4 add ./Lib/ruby/argcargv.i
p4 add ./Lib/ruby/attribute.i
p4 add ./Lib/ruby/carrays.i
p4 add ./Lib/ruby/cdata.i
p4 add ./Lib/ruby/cmalloc.i
p4 add ./Lib/ruby/cni.i
p4 add ./Lib/ruby/cpointer.i
p4 add ./Lib/ruby/cstring.i
p4 add ./Lib/ruby/director.swg
p4 add ./Lib/ruby/embed.i
p4 add ./Lib/ruby/exception.i
p4 add ./Lib/ruby/extconf.rb
p4 add ./Lib/ruby/extra-install.list
p4 add ./Lib/ruby/factory.i
p4 add ./Lib/ruby/file.i
p4 add ./Lib/ruby/jstring.i
p4 add ./Lib/ruby/Makefile.swig
p4 add ./Lib/ruby/progargcargv.i
p4 add ./Lib/ruby/ruby.swg
p4 add ./Lib/ruby/rubyapi.swg
p4 add ./Lib/ruby/rubyautodoc.swg
p4 add ./Lib/ruby/rubyclasses.swg
p4 add ./Lib/ruby/rubycomplex.swg
p4 add ./Lib/ruby/rubycontainer.swg
p4 add ./Lib/ruby/rubycontainer_extended.swg
p4 add ./Lib/ruby/rubydef.swg
p4 add ./Lib/ruby/rubyerrors.swg
p4 add ./Lib/ruby/rubyfragments.swg
p4 add ./Lib/ruby/rubyhead.swg
p4 add ./Lib/ruby/rubyinit.swg
p4 add ./Lib/ruby/rubyiterators.swg
p4 add ./Lib/ruby/rubykw.swg
p4 add ./Lib/ruby/rubymacros.swg
p4 add ./Lib/ruby/rubyopers.swg
p4 add ./Lib/ruby/rubyprimtypes.swg
p4 add ./Lib/ruby/rubyrun.swg
p4 add ./Lib/ruby/rubyruntime.swg
p4 add ./Lib/ruby/rubystdautodoc.swg
p4 add ./Lib/ruby/rubystdcommon.swg
p4 add ./Lib/ruby/rubystdfunctors.swg
p4 add ./Lib/ruby/rubystrings.swg
p4 add ./Lib/ruby/rubytracking.swg
p4 add ./Lib/ruby/rubytypemaps.swg
p4 add ./Lib/ruby/rubyuserdir.swg
p4 add ./Lib/ruby/rubywstrings.swg
p4 add ./Lib/ruby/std_alloc.i
p4 add ./Lib/ruby/std_basic_string.i
p4 add ./Lib/ruby/std_char_traits.i
p4 add ./Lib/ruby/std_common.i
p4 add ./Lib/ruby/std_complex.i
p4 add ./Lib/ruby/std_container.i
p4 add ./Lib/ruby/std_deque.i
p4 add ./Lib/ruby/std_except.i
p4 add ./Lib/ruby/std_functors.i
p4 add ./Lib/ruby/std_ios.i
p4 add ./Lib/ruby/std_iostream.i
p4 add ./Lib/ruby/std_list.i
p4 add ./Lib/ruby/std_map.i
p4 add ./Lib/ruby/std_multimap.i
p4 add ./Lib/ruby/std_multiset.i
p4 add ./Lib/ruby/std_pair.i
p4 add ./Lib/ruby/std_queue.i
p4 add ./Lib/ruby/std_set.i
p4 add ./Lib/ruby/std_sstream.i
p4 add ./Lib/ruby/std_stack.i
p4 add ./Lib/ruby/std_streambuf.i
p4 add ./Lib/ruby/std_string.i
p4 add ./Lib/ruby/std_vector.i
p4 add ./Lib/ruby/std_vectora.i
p4 add ./Lib/ruby/std_wstring.i
p4 add ./Lib/ruby/stl.i
p4 add ./Lib/ruby/timeval.i
p4 add ./Lib/ruby/typemaps.i
p4 add ./Lib/runtime.swg
p4 add ./Lib/shared_ptr.i
p4 add ./Lib/std/README
p4 add ./Lib/std/std_alloc.i
p4 add ./Lib/std/std_basic_string.i
p4 add ./Lib/std/std_carray.swg
p4 add ./Lib/std/std_char_traits.i
p4 add ./Lib/std/std_common.i
p4 add ./Lib/std/std_container.i
p4 add ./Lib/std/std_deque.i
p4 add ./Lib/std/std_except.i
p4 add ./Lib/std/std_ios.i
p4 add ./Lib/std/std_iostream.i
p4 add ./Lib/std/std_list.i
p4 add ./Lib/std/std_map.i
p4 add ./Lib/std/std_multimap.i
p4 add ./Lib/std/std_multiset.i
p4 add ./Lib/std/std_pair.i
p4 add ./Lib/std/std_queue.i
p4 add ./Lib/std/std_set.i
p4 add ./Lib/std/std_sstream.i
p4 add ./Lib/std/std_stack.i
p4 add ./Lib/std/std_streambuf.i
p4 add ./Lib/std/std_string.i
p4 add ./Lib/std/std_vector.i
p4 add ./Lib/std/std_vectora.i
p4 add ./Lib/std/std_wios.i
p4 add ./Lib/std/std_wiostream.i
p4 add ./Lib/std/std_wsstream.i
p4 add ./Lib/std/std_wstreambuf.i
p4 add ./Lib/std/std_wstring.i
p4 add ./Lib/std/_std_deque.i
p4 add ./Lib/stdint.i
p4 add ./Lib/std_except.i
p4 add ./Lib/stl.i
p4 add ./Lib/swig.swg
p4 add ./Lib/swigarch.i
p4 add ./Lib/swigerrors.swg
p4 add ./Lib/swiginit.swg
p4 add ./Lib/swiglabels.swg
p4 add ./Lib/swigrun.i
p4 add ./Lib/swigrun.swg
p4 add ./Lib/swigwarn.swg
p4 add ./Lib/swigwarnings.swg
p4 add ./Lib/tcl/attribute.i
p4 add ./Lib/tcl/carrays.i
p4 add ./Lib/tcl/cdata.i
p4 add ./Lib/tcl/cmalloc.i
p4 add ./Lib/tcl/cni.i
p4 add ./Lib/tcl/cpointer.i
p4 add ./Lib/tcl/cstring.i
p4 add ./Lib/tcl/cwstring.i
p4 add ./Lib/tcl/exception.i
p4 add ./Lib/tcl/factory.i
p4 add ./Lib/tcl/jstring.i
p4 add ./Lib/tcl/mactclinit.c
p4 add ./Lib/tcl/mactkinit.c
p4 add ./Lib/tcl/Makefile.in
p4 add ./Lib/tcl/std_common.i
p4 add ./Lib/tcl/std_deque.i
p4 add ./Lib/tcl/std_except.i
p4 add ./Lib/tcl/std_map.i
p4 add ./Lib/tcl/std_pair.i
p4 add ./Lib/tcl/std_string.i
p4 add ./Lib/tcl/std_vector.i
p4 add ./Lib/tcl/std_wstring.i
p4 add ./Lib/tcl/stl.i
p4 add ./Lib/tcl/tcl8.swg
p4 add ./Lib/tcl/tclapi.swg
p4 add ./Lib/tcl/tclerrors.swg
p4 add ./Lib/tcl/tclfragments.swg
p4 add ./Lib/tcl/tclinit.swg
p4 add ./Lib/tcl/tclinterp.i
p4 add ./Lib/tcl/tclkw.swg
p4 add ./Lib/tcl/tclmacros.swg
p4 add ./Lib/tcl/tclopers.swg
p4 add ./Lib/tcl/tclprimtypes.swg
p4 add ./Lib/tcl/tclresult.i
p4 add ./Lib/tcl/tclrun.swg
p4 add ./Lib/tcl/tclruntime.swg
p4 add ./Lib/tcl/tclsh.i
p4 add ./Lib/tcl/tclstrings.swg
p4 add ./Lib/tcl/tcltypemaps.swg
p4 add ./Lib/tcl/tcluserdir.swg
p4 add ./Lib/tcl/tclwstrings.swg
p4 add ./Lib/tcl/typemaps.i
p4 add ./Lib/tcl/wish.i
p4 add ./Lib/typemaps/attribute.swg
p4 add ./Lib/typemaps/carrays.swg
p4 add ./Lib/typemaps/cdata.swg
p4 add ./Lib/typemaps/cmalloc.swg
p4 add ./Lib/typemaps/cpointer.swg
p4 add ./Lib/typemaps/cstring.swg
p4 add ./Lib/typemaps/cstrings.swg
p4 add ./Lib/typemaps/cwstring.swg
p4 add ./Lib/typemaps/enumint.swg
p4 add ./Lib/typemaps/exception.swg
p4 add ./Lib/typemaps/factory.swg
p4 add ./Lib/typemaps/fragments.swg
p4 add ./Lib/typemaps/implicit.swg
p4 add ./Lib/typemaps/inoutlist.swg
p4 add ./Lib/typemaps/misctypes.swg
p4 add ./Lib/typemaps/primtypes.swg
p4 add ./Lib/typemaps/ptrtypes.swg
p4 add ./Lib/typemaps/README
p4 add ./Lib/typemaps/std_except.swg
p4 add ./Lib/typemaps/std_string.swg
p4 add ./Lib/typemaps/std_strings.swg
p4 add ./Lib/typemaps/std_wstring.swg
p4 add ./Lib/typemaps/string.swg
p4 add ./Lib/typemaps/strings.swg
p4 add ./Lib/typemaps/swigmacros.swg
p4 add ./Lib/typemaps/swigobject.swg
p4 add ./Lib/typemaps/swigtype.swg
p4 add ./Lib/typemaps/swigtypemaps.swg
p4 add ./Lib/typemaps/traits.swg
p4 add ./Lib/typemaps/typemaps.swg
p4 add ./Lib/typemaps/valtypes.swg
p4 add ./Lib/typemaps/void.swg
p4 add ./Lib/typemaps/wstring.swg
p4 add ./Lib/uffi/uffi.swg
p4 add ./Lib/wchar.i
p4 add ./Lib/windows.i
p4 add ./Lib/xml/typemaps.i
p4 add ./Lib/xml/xml.swg
p4 add ./swig.exe
