#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'hl2'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):

	source = ['main.cpp']
	includes = ['../public']
	defines = []
	libs = []

	if bld.env.DEST_OS != 'win32':
		libs += [ 'DL' ]
	else:
		libs += ['USER32', 'SHELL32']
		source += ['launcher_main.rc']

	install_path = bld.env.PREFIX
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

