#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'particles'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'builtin_constraints.cpp',
		'builtin_initializers.cpp',
		'builtin_particle_emitters.cpp',
		'builtin_particle_forces.cpp',
		'addbuiltin_ops.cpp',
		'builtin_particle_ops.cpp',
		'builtin_particle_render_ops.cpp',
		'particle_sort.cpp',		
		'particles.cpp',
		'psheet.cpp'
	]

	includes = [
		'.',
		'../public',
		'../public/tier1',
		'../public/tier0'
	]

	defines = []

	libs = []

	install_path = bld.env.PREFIX

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

