#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os
import vpc_parser

top = '.'
PROJECT_NAME = 'gamepadui'

def options(opt):
	return

games = {
	'hl2': ['gamepadui_base.vpc', 'gamepadui_hl2.vpc'],
	'hl2mp': ['gamepadui_base.vpc', 'gamepadui_hl2.vpc'],
	'hl1': ['gamepadui_base.vpc', 'gamepadui_hl2.vpc'],
	'episodic': ['gamepadui_base.vpc', 'gamepadui_episodic.vpc'],
	'portal': ['gamepadui_base.vpc', 'gamepadui_portal.vpc'],
	'hl1mp': ['gamepadui_base.vpc', 'gamepadui_hl2.vpc'], 
	'cstrike': ['gamepadui_base.vpc', 'gamepadui_hl2.vpc'],
	'dod': ['gamepadui_base.vpc', 'gamepadui_hl2.vpc']
}

def configure(conf):
	game = conf.options.GAMES
	conf.env.GAMES = game

	conf.env.append_unique('DEFINES', ['DISABLE_STEAM=1'])

	if game not in games.keys():
		conf.fatal("Couldn't find game: ", game)

def build(bld):
	game = vpc_parser.parse_vpcs( bld.env, games[bld.env.GAMES], '../..' )

	includes = [
		'.',
		'game_controls',
		'../../common',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../vgui2/vgui_controls',
		'../shared',
        '../game/gamepadui'
	]

	libs = [
		'tier0',
		'particles',
		'dmxloader',
		'vgui_controls',
		'matsys_controls',
		'tier1',
		'tier2',
		'tier3',
		'mathlib',
		'vstdlib',
		'choreoobjects',
		'steam_api',
		'bitmap',
		'vtf',
		'RT',
		'ZLIB'
	]

	install_path = bld.env.PREFIX
	if bld.env.DEST_OS != 'android':
		install_path += '/'+bld.env.GAMES+'/bin'

	#source = [ 'in_touch.cpp' ]
	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	source = game["sources"] + ['../../public/tier0/memoverride.cpp']
	includes += game["includes"]
	defines = game["defines"]

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

