#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'choreoobjects'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'../game/shared/choreoactor.cpp',
		'../game/shared/choreochannel.cpp',
		'../game/shared/choreoevent.cpp',
		'../game/shared/choreoscene.cpp',
		'../game/shared/sceneimage.cpp'
	]

	includes = [
		'.',
		'../game/shared',
		'../utils/common',
		'../public/tier0',
		'../public/tier1',
		'../public',
		'../common'
	]

	defines = []

	libs = []

	install_path = bld.env.PREFIX

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

