#ifndef _INCLUDED_ASW_MEDALS_SHARED_H
#define _INCLUDED_ASW_MEDALS_SHARED_H
#ifdef _WIN32
#pragma once
#endif

enum {
	MEDAL_NONE = 0,
	MEDAL_BLOOD_HEART,	// 1
	MEDAL_CLEAR_FIRING,
	MEDAL_SHIELDBUG_ASSASSIN,
	MEDAL_EXPLOSIVES_MERIT,
	MEDAL_RECKLESS_EXPLOSIVES_MERIT,
	MEDAL_SHARPSHOOTER,
	MEDAL_LIFESAVER,
	MEDAL_PERFECT,
	//MEDAL_STATIC_DEFENSE,
	MEDAL_ALL_SURVIVE_A_MISSION,
	MEDAL_PEST_CONTROL, // 10
	MEDAL_BUGSTOMPER,
	MEDAL_EXTERMINATOR,
	MEDAL_FIREFIGHTER,
	MEDAL_IRON_FIST,
	MEDAL_KILLING_SPREE,
	MEDAL_COLLATERAL_DAMAGE,
	MEDAL_IRON_DAGGER,
	MEDAL_PYROMANIAC,
	MEDAL_HUNTER,		
	//MEDAL_HYBRID_WEAPONS_EXPERT,	
	MEDAL_SMALL_ARMS_SPECIALIST,	// 20
	MEDAL_GUNFIGHTER,
	//MEDAL_LAST_STAND,
	MEDAL_INCENDIARY_DEFENCE,
	MEDAL_IRON_HAMMER,
	MEDAL_SWARM_SUPPRESSION,
	MEDAL_IRON_SWORD,
	MEDAL_BLOOD_HALO,
	MEDAL_SILVER_HALO,
	MEDAL_GOLDEN_HALO,
	MEDAL_ELECTRICAL_SYSTEMS_EXPERT,  
	MEDAL_COMPUTER_SYSTEMS_EXPERT,	 // 30
	MEDAL_EASY_CAMPAIGN,
	MEDAL_NORMAL_CAMPAIGN,
	MEDAL_HARD_CAMPAIGN,
	MEDAL_INSANE_CAMPAIGN,
	MEDAL_IAF_TRAINING,
	MEDAL_IAF_COMBAT_HONORS,
	MEDAL_IAF_BATTLE_HONORS,
	MEDAL_IAF_CAMPAIGN_HONORS,
	MEDAL_IAF_WARTIME_SERVICE, 
	MEDAL_PROFESSIONAL, // 40
	MEDAL_NEMESIS,
	MEDAL_RETRIBUTION,
	MEDAL_IAF_HERO,
	MEDAL_SPEED_RUN_LANDING_BAY,	// 44 start of speedrun medals
	MEDAL_SPEED_RUN_OUTSIDE,
	MEDAL_SPEED_RUN_PLANT,
	MEDAL_SPEED_RUN_OFFICE,
	MEDAL_SPEED_RUN_DESCENT,
	MEDAL_SPEED_RUN_SEWERS,	
	MEDAL_SPEED_RUN_MINE,   // 50
	MEDAL_SPEED_RUN_QUEEN_LAIR,
	MEDAL_OUTSTANDING_EXECUTION_LANDING_BAY,	// 52 start of outstanding medals
	MEDAL_OUTSTANDING_EXECUTION_OUTSIDE,
	MEDAL_OUTSTANDING_EXECUTION_PLANT,
	MEDAL_OUTSTANDING_EXECUTION_OFFICE,
	MEDAL_OUTSTANDING_EXECUTION_LABS,
	MEDAL_OUTSTANDING_EXECUTION_SEWERS,
	MEDAL_OUTSTANDING_EXECUTION_MINE,
	MEDAL_OUTSTANDING_EXECUTION_QUEEN_LAIR,		// 59

	LAST_MEDAL,
};

int GetXPForMedal( int nMedal );

#endif // _INCLUDED_ASW_MEDALS_SHARED_H