#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'inputsystem'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('VERSION_SAFE_STEAM_API_INTERFACES',1)

def build(bld):
	source = [
		'inputsystem.cpp',
		'joystick_sdl.cpp',
		#'novint.cpp', #			[$WIN32]
		'key_translation.cpp',
		'steamcontroller.cpp'
	]

	includes = [
		'.',
		'../common',
		'../public',
		'../public/tier0',
		'../thirdparty/SDL2'
	]	

	defines = []

	libs = ['tier0','tier1','tier2','vstdlib','SDL2','steam_api']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

